### ISSUE TITLE
Incorrect type on  `\Spatie\SlackAlerts\Facades\SlackAlert::to()`

### ISSUE THREAD

**Issue by dpash** [spatie/laravel-slack-alerts#31]
Given

       SlackAlert::to($webhook_url)
                    ->message($message);

Psalm reports an error:

    ERROR: UndefinedMethod - Example.php:44:31 - Method Spatie\SlackAlerts\Facades\SlackAlert::message does not exist (see https://psalm.dev/022)
                            ->message($message);

Additionally PHPStorm complains that you shouldn't call a static method dynamically, hinting at the problem.

The documentation on `\Spatie\SlackAlerts\Facades\SlackAlert` is

     * @method static self to(string $text)

but I think this should be changed to

     * @method static \Spatie\SlackAlerts\SlackAlert to(string $text)

**Comment by freekmurze** [comment]
Feel free to submit a PR to fix this.

**Comment by dpash** [comment]
I'm sorry, did you close this without fixing it?

**Comment by Nielsvanpach** [comment]
Feel free to submit a pull request to fix this.

**Comment by dpash** [comment]
The issue still exists. This should not be closed. Telling me to create a PR doesn't help anyone having the same issue. It certainly isn't completed. It's WONTFIX.

**Comment by Nielsvanpach** [comment]
We develop packages for our own use and choose to open source them to assist others who may benefit. However, this does not imply an obligation on our part to provide free(!) work for resolving issues you are having or implementing features others need.

As mentioned previously, we are willing to merge a pull request that addresses the problem you are experiencing with Psalm. 
Since I personally don't use this package with Psalm, I don't feel the urge to invest my spare time in fixing this.

Additionally, expressing dissatisfaction and giving a 👎  does not encourage any open source maintainer to fulfil your requests.

**Comment by dpash** [comment]
I'm not asking you to do anything. I'm asking you to not close an issue when the problem still remains.
